### PR TITLE
support freecad v0.17

### PR DESCRIPTION
**Pull request by mingxi**

### CODE REVIEW

**Comment by hamish2014** [comment]
Hi Mingxi,

I have looked over the merge request, thank you.
Has Python3 support been added to FreeCAD?

**Comment by mingxi** [comment]
@hamish2014 
Thanks for your response.
I confirmed that Freedcad v0.17 was using python2 and qt5.
I got the error "AttributeError: type object 'PySide2.QtWidgets.QApplication' has no attribute 'UnicodeUTF8''' before.
So I pushed the commit.

**Comment by hamish2014** [comment]
@mingxi 
Interesting:
both drawingDimensioning/toleranceDialog.py and drawingDimensioning/textAddDialog.py
were generated automatically using pyside-uic 0.2.15 running on PySide 1.2.2.
Bash command:
`
$ pyside-uic textAddDialog.ui >toleranceDialog.py
`

Questions:
1) Which Pyside version is running on your system?
2) Did you edit the files by hand, or where they also generated using pyside-uic?

**Comment by mingxi** [comment]
@hamish2014 
**1. Which Pyside version is running on your system?**
_PySide2 version is '5.9.0~a1', it was default integrated to FreeCAD v0.17 for mac OSX._

**2. Did you edit the files by hand, or where they also generated using pyside-uic?**
_After I installed FreeCAD v0.17, I installed FreeCAD_drawing_dimensioning through the addon manager.
I got the 'AttributeError' when I relaunched the FreeCAD.
Then I fixed it by manually editing the files._

**Comment by hamish2014** [comment]
Hi @mingxi and @looooo,
Both you have submitted merge pull requests, addressing similar issues.
Looooo's seem to be more comprehensive so I am intended to go with that.
Looooo's what platform have you tested your updates on?

**Comment by looooo** [comment]
I test with py3/qt5 Linux. But not all worked, so there is still work needed to support this plattform.

**Comment by hamish2014** [comment]
I am going to go with @looooo  pull request.
Thank you for efforts @mingxi

**Pull request closed without merging**
