### PR TITLE
Added angle dimension from 3 points, and added some comments to angularD...

### PR DESCRIPTION
**Pull request by crobarcro**
...imension.py

This adds another angular dimension tool, but where you select three points, the centre and two others instead of two lines. This helps with drawing angles between features on circles which do not have radially pointing edges.

### CODE REVIEW

**Comment by hamish2014** [comment]
Okay, I am agree with the need to for constructing an angular dimension from 3 points.
I am not going to merge the pull request however, since I believe a better solution compared to making an entire new tool, would be to alter the existing angular dimension tool as to allow the user to either select 2 lines or 3 points.

**Comment by crobarcro** [comment]
Ok, this is also a good solution. I think it's nice and quick to just have the option right there in the menu though.

**Comment by hamish2014** [comment]
Sure, the drawing dimensioning workbench is open source, so please modify the code to your preference!
I also take my hat off to you for being pro-active;
Many users would just make a feature request, but you are willing spend the time and actually implement that feature yourself.
Well done!

**Comment by crobarcro** [comment]
Well, I needed it, and you'd done most of the hard work! I'd rather not fork the sources, so when you implement an alternative solution, I'll probably revert to that.

**Pull request closed without merging**
